name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que usas para producción

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CATEDRA3FRONTEND }}
          projectId: catedra3frontend
